### ISSUE TITLE
arg less main() for `pip install -e`

### ISSUE THREAD

**Issue by yunjunz** [yunjunz/MintPy#5]
It seems when installing mintpy using `pip install -e MintPy`, the command-line options are not working:

```bash
(insar) kyushu:~/data/offset4motion/SaltonSeaSenDT173/merged/test/20191220_20201220>$ view.py off3_snr.bip -v 0 100 --flip-lr
Traceback (most recent call last):
  File "/home/zyunjun/tools/miniconda3/envs/insar/bin/view.py", line 33, in <module>
    sys.exit(load_entry_point('mintpy', 'console_scripts', 'view.py')())
  File "/home/zyunjun/tools/MintPy/mintpy/view.py", line 1663, in main
    obj.configure()
  File "/home/zyunjun/tools/MintPy/mintpy/view.py", line 1538, in configure
    inps = cmd_line_parse(self.iargs)
  File "/home/zyunjun/tools/MintPy/mintpy/view.py", line 175, in cmd_line_parse
    geo_opt_names = list(set(geo_opt_names) & set(iargs))
TypeError: 'NoneType' object is not iterable
```

The solution could be using the `sys.argv` all the time as suggested in https://github.com/insarlab/MintPy/issues/652. `view.py` has the most complicated usage of `iargs`. If the following 3 scenarios works, then it should be safe to translate the rest of mintpy to arg less main() style:
1. view.py velocity.h5 -v 0 3 --flip-lr      # command line in terminal
2. view.main('velocity.h5 -v 0 3 --flip-lr'.split())   # main function call in python
3. view and tsview interactive jupyter notebook: https://github.com/insarlab/MintPy-tutorial/tree/main/visualization

**Comment by jhkennedy** [comment]
@yunjunz this issues is caused by trying to convert `iargs` to s `set` when it's value is `None` here:
https://github.com/yunjunz/MintPy/blob/main/mintpy/view.py#L175

```python
>>> set(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```
You'll likewise have problems trying to `join(None)` here:
https://github.com/yunjunz/MintPy/blob/main/mintpy/view.py#L185
```python
>>> ' '.join(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only join an iterable
```


In the old install, you set `iargs=sys.argv[1:]`:
https://github.com/yunjunz/MintPy/blob/main/mintpy/view.py#L1677

So if you wanted to have the old behavior, you could do the same with a:

```python
if iargs is None:
    iargs = sys.argv[1:]
```

This will have issues, however, where `sys.argv` is related to *how the interpreter* was launched. So you'd probably actually just want:
```python
if iargs is None:
    iargs = []
```
which will look like the old case where the script was invoked without any arguments. 

---

In general, I'd caution against doing operations against `sys.argv` and instead would suggest the logic would be better done looking at your parsed args (`inps`) as argparse handles a lot of gotchas with `sys.argv`. 
https://github.com/yunjunz/MintPy/blob/main/mintpy/view.py#L141

**Comment by yunjunz** [comment]
Thank you @jhkennedy for the diagnose. The following modification seems to work in all three scenarios for versions installed via pip or path setup. I have issued a PR for it.

```python
# save argv (to check the manually specified arguments)
# use iargs        for python call
# use sys.argv[1:] for command line call
inps.argv = iargs if iargs else sys.argv[1:]
```
